"""empty message

Revision ID: 1fc9ea36a3b9
Revises: eb94e22b9b25
Create Date: 2022-11-01 16:42:26.199767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc9ea36a3b9'
down_revision = 'eb94e22b9b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_table', sa.Column('title', sa.String(length=120), nullable=False))
    op.drop_column('note_table', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_table', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('note_table', 'title')
    # ### end Alembic commands ###
