"""empty message

Revision ID: 9954e5c4de71
Revises: 53445d3a4d1f
Create Date: 2022-10-04 13:32:20.938374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9954e5c4de71'
down_revision = '53445d3a4d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_cookie', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_cookie')
    # ### end Alembic commands ###
