"""empty message

Revision ID: bd76c542ba27
Revises: 1fc9ea36a3b9
Create Date: 2022-11-01 16:45:40.791095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd76c542ba27'
down_revision = '1fc9ea36a3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_table', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'note_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_table', type_='foreignkey')
    op.drop_column('note_table', 'user_id')
    # ### end Alembic commands ###
