"""empty message

Revision ID: eb94e22b9b25
Revises: 595235bb0f37
Create Date: 2022-11-01 15:17:03.206294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb94e22b9b25'
down_revision = '595235bb0f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('text', sa.String(length=1200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tag',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note_table.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_table.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tag')
    op.drop_table('tag_table')
    op.drop_table('note_table')
    # ### end Alembic commands ###
